#!/usr/bin/env bash
#
#   CyberSecurity
#   Programmer: Renato Kopke
#
# set -ueo pipefail;

: ${docker=docker}

WHOAMI=$(whoami)

TEMP_FILE="$1"
TARGET_URL="$2"

REPORT_FILE=$TEMP_FILE
REPORT_FILE_JSON="$TEMP_FILE.json"

REPORT="report"

[ ! -d "$REPORT" ] && mkdir -m 0777 $REPORT; sleep 2

$docker ps -a -f status=exited -q | while read c; do $docker rm $c > /dev/null; done

docker pull owasp/zap2docker-live

mkdir -p /tmp/report && chmod 777 /tmp/$REPORT && chown ${whoami}:${whoami} /tmp/$REPORT

$docker run -v /tmp/$REPORT:/zap/wrk/:rw -t owasp/zap2docker-live zap-api-scan.py -t "$TARGET_URL" -g gen.conf -f openapi -d -r "$REPORT_FILE" -J "$REPORT_FILE_JSON"