# Generated by Django 3.2.9 on 2021-12-05 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('json_result', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('report_path', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
